name: "🏗️ Master Topic Plan"
description: "Plan and track a major technical pillar (3 days to 1 month+)."
title: "[Master]: Phase [x] - Topic [#]: (Topic Name)"
labels: ["tracking", "master-issue"]
assignees: ["YOUR_GITHUB_USERNAME"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🗺️ Master Roadmap
        Define your days below. Use the `- [x]` syntax to create interactive checkboxes.

  - type: input
    id: duration
    attributes:
      label: "⏱️ Estimated Duration"
      placeholder: "e.g., 5 Days, 2 Weeks"
    validations:
      required: true

  - type: textarea
    id: daily_plan
    attributes:
      label: "📅 Daily Execution Plan"
      description: "Customize the days to fit your specific study path for this topic."
      value: |
        - [ ] Day #: Execution Plan - 
        - [ ] Day #: Execution Plan -
        - [ ] Day #: Execution Plan -
        - [ ] Day #: Execution Plan -
        - [ ] Day #: Execution Plan -
        - [ ] Day #: Execution Plan -
        - [ ] Day #: Execution Plan -
    validations:
      required: true

  - type: checkboxes
    id: dod
    attributes:
      label: "✅ Final Mastery Check"
      options:
        - label: "I can build this from scratch without a tutorial."
        - label: "All related Daily Logs are linked below."
        - label: "All cloud resources have been deleted (Cost Check)."

   - type: input
    id: blog_url
    attributes:
      label: Blog Post URL
      description: Link to your blog post
      placeholder: https://yourblog.com/
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 🔗 Related Daily Logs
        *Reference your logs here: (e.g., Part of #101, #102)*
